spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect



  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}

  cache:
    type: redis

  redis:
    port: ${redis.port}
    host: ${redis.host}


defined:
  fcm:
    url: ${fcm.url}
    firebaseConfigPath: ${fcm.firebaseConfigPath}