spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}

  cache:
    type: redis

  redis:
    port: ${redis.port}
    host: ${redis.host}


defined:
  fcm:
    url: ${fcm.url}
    firebaseConfigPath: ${fcm.firebaseConfigPath}
  email:
    account: ${email.account}
    password: ${email.password}
  security:
    secretKey: ${security.secretKey}
    accessExpire: ${security.accessExpire}
    refreshExpire: ${security.refreshExpire}
